import crypto from 'node:crypto';
import { accountSessionSecret, signSession, verifySession } from './session-utils.js';

const clean=value=>String(value??'').trim();
const AUTH_URL='https://marketplace.leadconnectorhq.com/oauth/chooselocation';
const TOKEN_URL='https://services.leadconnectorhq.com/oauth/token';
const API_URL='https://services.leadconnectorhq.com';
const SCOPES=['locations.readonly','contacts.readonly','contacts.write','opportunities.readonly','opportunities.write','pipelines.readonly','users.readonly'];
export const GHL_WEBHOOK_PUBLIC_KEY=`-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAi2HR1srL4o18O8BRa7gVJY7G7bupbN3H9AwJrHCDiOg=
-----END PUBLIC KEY-----`;

export function ghlConfig(){const clientId=clean(process.env.GHL_CLIENT_ID),clientSecret=clean(process.env.GHL_CLIENT_SECRET),redirectUri=clean(process.env.GHL_REDIRECT_URI),encryptionSecret=clean(process.env.GHL_TOKEN_ENCRYPTION_KEY)||accountSessionSecret();return clientId&&clientSecret&&redirectUri&&encryptionSecret?{clientId,clientSecret,redirectUri,encryptionSecret,scopes:SCOPES}:null}
const cipherKey=secret=>crypto.createHash('sha256').update(String(secret)).digest();
export function encryptGhlToken(value,secret){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',cipherKey(secret),iv),encrypted=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]),tag=cipher.getAuthTag();return`v1.${iv.toString('base64url')}.${tag.toString('base64url')}.${encrypted.toString('base64url')}`}
export function decryptGhlToken(value,secret){const[v,iv,tag,data]=String(value||'').split('.');if(v!=='v1'||!iv||!tag||!data)throw new Error('Stored CRM token is invalid.');const decipher=crypto.createDecipheriv('aes-256-gcm',cipherKey(secret),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8')}
export function verifyGhlWebhookSignature(payload,signature){try{return Boolean(signature)&&crypto.verify(null,Buffer.from(String(payload),'utf8'),GHL_WEBHOOK_PUBLIC_KEY,Buffer.from(String(signature),'base64'))}catch{return false}}

export function createGhlAuthorizationUrl(accountId){const c=ghlConfig();if(!c)throw new Error('CRM Connector is not configured.');const state=signSession({purpose:'ghl-oauth',accountId},accountSessionSecret(),10*60);return`${AUTH_URL}?${new URLSearchParams({response_type:'code',client_id:c.clientId,redirect_uri:c.redirectUri,scope:c.scopes.join(' '),state})}`}
export function verifyGhlOAuthState(state,accountId){const p=verifySession(state,accountSessionSecret());return Boolean(p?.purpose==='ghl-oauth'&&p?.accountId===accountId)}
async function tokenRequest(values){const c=ghlConfig();if(!c)throw new Error('CRM Connector is not configured.');const response=await fetch(TOKEN_URL,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded',Version:'v3'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,...values})}),payload=await response.json().catch(()=>({}));if(!response.ok||!payload.access_token){const e=new Error(payload.error_description||payload.message||payload.error||'CRM token request failed.');e.status=response.status||400;e.payload=payload;throw e}return payload}
export const exchangeGhlCode=code=>{const c=ghlConfig();return tokenRequest({grant_type:'authorization_code',code:clean(code),user_type:'Location',redirect_uri:c.redirectUri})};
export const refreshGhlTokens=refreshToken=>{const c=ghlConfig();return tokenRequest({grant_type:'refresh_token',refresh_token:clean(refreshToken),user_type:'Location',redirect_uri:c.redirectUri})};
export const ghlTokenExpiry=tokens=>new Date(Date.now()+(Number(tokens.expires_in)||86399)*1000).toISOString();

async function request(accessToken,path,{method='GET',query,body}={}){const suffix=query?`?${new URLSearchParams(Object.entries(query).filter(([,v])=>v!==undefined&&v!==null&&v!=='')).toString()}`:'';const response=await fetch(`${API_URL}${path}${suffix}`,{method,headers:{Accept:'application/json',Authorization:`Bearer ${accessToken}`,Version:'2021-07-28',...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)}),text=await response.text();let payload={};try{payload=text?JSON.parse(text):{}}catch{}if(!response.ok){const e=new Error(payload.message||payload.error||'CRM API request failed.');e.status=response.status||400;e.payload=payload;throw e}return payload}
const validId=(value,label='record')=>{const id=clean(value);if(!/^[A-Za-z0-9_-]{5,100}$/.test(id))throw Object.assign(new Error(`CRM ${label} ID is invalid.`),{status:422});return id};
export async function getGhlLocation(accessToken,locationId){const p=await request(accessToken,`/locations/${validId(locationId,'location')}`);return p.location||p}
export async function listGhlContacts(accessToken,locationId){const p=await request(accessToken,'/contacts/',{query:{locationId,limit:100}});return Array.isArray(p.contacts)?p.contacts:[]}
export async function saveGhlContact(accessToken,locationId,input={}){const id=clean(input.id),body={locationId,firstName:clean(input.firstName).slice(0,120),lastName:clean(input.lastName).slice(0,120),email:clean(input.email).slice(0,320),phone:clean(input.phone).slice(0,80),companyName:clean(input.companyName).slice(0,200),source:'Creative Creatures'};Object.keys(body).forEach(k=>body[k]===''&&delete body[k]);const p=await request(accessToken,id?`/contacts/${validId(id,'contact')}`:'/contacts/',{method:id?'PUT':'POST',body});return p.contact||p}
export async function archiveGhlContact(accessToken,id){await request(accessToken,`/contacts/${validId(id,'contact')}`,{method:'DELETE'});return true}
export async function listGhlPipelines(accessToken,locationId){const p=await request(accessToken,'/opportunities/pipelines',{query:{locationId}});return Array.isArray(p.pipelines)?p.pipelines:[]}
export async function listGhlOpportunities(accessToken,locationId,pipelineId=''){const p=await request(accessToken,'/opportunities/search',{query:{location_id:locationId,pipeline_id:pipelineId,limit:100}});return Array.isArray(p.opportunities)?p.opportunities:[]}
export async function saveGhlOpportunity(accessToken,locationId,input={}){const id=clean(input.id),body={locationId,pipelineId:validId(input.pipelineId,'pipeline'),pipelineStageId:validId(input.pipelineStageId,'pipeline stage'),name:clean(input.name).slice(0,240),status:['open','won','lost','abandoned','all'].includes(clean(input.status).toLowerCase())?clean(input.status).toLowerCase():'open',contactId:validId(input.contactId,'contact'),monetaryValue:Number(input.monetaryValue)||0};const p=await request(accessToken,id?`/opportunities/${validId(id,'opportunity')}`:'/opportunities',{method:id?'PUT':'POST',body});return p.opportunity||p}
export async function archiveGhlOpportunity(accessToken,id){await request(accessToken,`/opportunities/${validId(id,'opportunity')}`,{method:'DELETE'});return true}
