import crypto from 'node:crypto';
import { accountSessionSecret, signSession, verifySession } from './session-utils.js';

const clean=value=>String(value??'').trim();
const AUTH_URL='https://auth.atlassian.com/authorize';
const TOKEN_URL='https://auth.atlassian.com/oauth/token';
const RESOURCES_URL='https://api.atlassian.com/oauth/token/accessible-resources';
const SCOPES=['offline_access','read:jira-work','write:jira-work','read:jira-user'];

export function jiraConfig(){
  const clientId=clean(process.env.JIRA_CLIENT_ID),clientSecret=clean(process.env.JIRA_CLIENT_SECRET),redirectUri=clean(process.env.JIRA_REDIRECT_URI);
  const encryptionSecret=clean(process.env.JIRA_TOKEN_ENCRYPTION_KEY)||accountSessionSecret();
  return clientId&&clientSecret&&redirectUri&&encryptionSecret?{clientId,clientSecret,redirectUri,encryptionSecret}:null;
}
function cipherKey(secret){return crypto.createHash('sha256').update(String(secret)).digest()}
export function encryptJiraToken(value,secret){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',cipherKey(secret),iv),data=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return`v1.${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${data.toString('base64url')}`}
export function decryptJiraToken(value,secret){const[v,iv,tag,data]=String(value||'').split('.');if(v!=='v1'||!iv||!tag||!data)throw new Error('Stored Jira token is invalid.');const decipher=crypto.createDecipheriv('aes-256-gcm',cipherKey(secret),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8')}
export function createJiraAuthorizationUrl(accountId){const c=jiraConfig();if(!c)throw new Error('Jira is not configured.');const state=signSession({purpose:'jira-oauth',accountId},accountSessionSecret(),10*60);return`${AUTH_URL}?${new URLSearchParams({audience:'api.atlassian.com',client_id:c.clientId,scope:SCOPES.join(' '),redirect_uri:c.redirectUri,state,response_type:'code',prompt:'consent'})}`}
export function verifyJiraOAuthState(state,accountId){const p=verifySession(state,accountSessionSecret());return Boolean(p?.purpose==='jira-oauth'&&p?.accountId===accountId)}
async function tokenRequest(body){const c=jiraConfig();if(!c)throw new Error('Jira is not configured.');const response=await fetch(TOKEN_URL,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:c.clientId,client_secret:c.clientSecret,...body})}),payload=await response.json().catch(()=>({}));if(!response.ok||!payload.access_token){const e=new Error(payload.error_description||payload.error||'Jira token request failed.');e.status=response.status||400;throw e}return payload}
export const exchangeJiraCode=code=>tokenRequest({grant_type:'authorization_code',code:clean(code),redirect_uri:jiraConfig()?.redirectUri||''});
export const refreshJiraTokens=refreshToken=>tokenRequest({grant_type:'refresh_token',refresh_token:clean(refreshToken)});
export function jiraTokenExpiry(tokens){return new Date(Date.now()+Math.max(60,Number(tokens?.expires_in)||3600)*1000).toISOString()}
async function jiraJson(url,{accessToken,method='GET',body}={}){const response=await fetch(url,{method,headers:{Accept:'application/json',Authorization:`Bearer ${accessToken}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),payload=await response.json().catch(()=>({}));if(!response.ok){const messages=[...(payload.errorMessages||[]),...Object.values(payload.errors||{})].filter(Boolean);const e=new Error(messages.join(' | ')||payload.message||'Jira API request failed.');e.status=response.status||400;throw e}return payload}
const base=cloudId=>`https://api.atlassian.com/ex/jira/${encodeURIComponent(clean(cloudId))}/rest/api/3`;
export async function listJiraResources(accessToken){const rows=await jiraJson(RESOURCES_URL,{accessToken});return(Array.isArray(rows)?rows:[]).map(x=>({id:clean(x.id),name:clean(x.name),url:clean(x.url),avatarUrl:clean(x.avatarUrl),scopes:Array.isArray(x.scopes)?x.scopes:[]})).filter(x=>x.id)}
export const getJiraCurrentUser=(accessToken,cloudId)=>jiraJson(`${base(cloudId)}/myself`,{accessToken});
export async function listJiraProjects(accessToken,cloudId){const p=await jiraJson(`${base(cloudId)}/project/search?maxResults=100&orderBy=name`,{accessToken});return(p.values||[]).map(x=>({id:clean(x.id),key:clean(x.key),name:x.name||'Project',projectTypeKey:x.projectTypeKey||'',simplified:Boolean(x.simplified),style:x.style||'',avatarUrl:x.avatarUrls?.['48x48']||''}))}
export async function listJiraIssues(accessToken,cloudId){const q=new URLSearchParams({jql:'order by updated DESC',maxResults:'100',fields:'summary,status,priority,assignee,project,issuetype,created,updated,duedate,resolutiondate'});const p=await jiraJson(`${base(cloudId)}/search/jql?${q}`,{accessToken});return(p.issues||[]).map(x=>normalizeIssue(x))}
export async function listJiraIssueTypes(accessToken,cloudId,projectIdOrKey){const p=await jiraJson(`${base(cloudId)}/issue/createmeta/${encodeURIComponent(clean(projectIdOrKey))}/issuetypes?maxResults=100`,{accessToken});return(p.values||[]).map(x=>({id:clean(x.id),name:x.name||'Issue',description:x.description||'',subtask:Boolean(x.subtask)}))}
function adf(text){return clean(text)?{type:'doc',version:1,content:clean(text).split(/\n+/).map(line=>({type:'paragraph',content:[{type:'text',text:line}]}))}:null}
function normalizeIssue(x){const f=x.fields||{};return{id:clean(x.id),key:clean(x.key),summary:f.summary||'Issue',status:f.status?.name||'',statusCategory:f.status?.statusCategory?.key||'',priority:f.priority?.name||'',assigneeId:clean(f.assignee?.accountId),assigneeName:f.assignee?.displayName||'',projectId:clean(f.project?.id),projectKey:clean(f.project?.key),projectName:f.project?.name||'',issueTypeId:clean(f.issuetype?.id),issueType:f.issuetype?.name||'',created:f.created||null,updated:f.updated||null,dueDate:f.duedate||null,resolutionDate:f.resolutiondate||null}}
export async function saveJiraIssue(accessToken,cloudId,{issueKey,projectKey,issueTypeId,summary,description,dueDate}){const fields={summary:clean(summary)};if(!fields.summary)throw Object.assign(new Error('Issue summary is required.'),{status:422});if(!issueKey){if(!clean(projectKey)||!clean(issueTypeId))throw Object.assign(new Error('Project and issue type are required.'),{status:422});fields.project={key:clean(projectKey)};fields.issuetype={id:clean(issueTypeId)}}if(description!==undefined)fields.description=adf(description);if(dueDate!==undefined)fields.duedate=clean(dueDate)||null;const p=await jiraJson(`${base(cloudId)}/issue${issueKey?`/${encodeURIComponent(clean(issueKey))}`:''}`,{accessToken,method:issueKey?'PUT':'POST',body:{fields}});return issueKey?{id:'',key:clean(issueKey),updated:true}:p}
export async function listJiraTransitions(accessToken,cloudId,issueKey){const p=await jiraJson(`${base(cloudId)}/issue/${encodeURIComponent(clean(issueKey))}/transitions`,{accessToken});return(p.transitions||[]).map(x=>({id:clean(x.id),name:x.name||'Transition',to:x.to?.name||''}))}
export const transitionJiraIssue=(accessToken,cloudId,issueKey,transitionId)=>jiraJson(`${base(cloudId)}/issue/${encodeURIComponent(clean(issueKey))}/transitions`,{accessToken,method:'POST',body:{transition:{id:clean(transitionId)}}});
