import crypto from 'node:crypto';
import { accountSessionSecret, signSession, verifySession } from './session-utils.js';

const clean=value=>String(value??'').trim();
const AUTHORIZE_URL='https://auth.monday.com/oauth2/authorize';
const NEW_TOKEN_URL='https://auth.monday.com/oauth_ms/oauth/token';
const LEGACY_TOKEN_URL='https://auth.monday.com/oauth2/token';
const REVOKE_URL='https://auth.monday.com/oauth_ms/oauth/revoke';
const API_URL='https://api.monday.com/v2';
const API_VERSION='2026-07';

export function mondayConfig(){
  const clientId=clean(process.env.MONDAY_CLIENT_ID),clientSecret=clean(process.env.MONDAY_CLIENT_SECRET),redirectUri=clean(process.env.MONDAY_REDIRECT_URI),encryptionSecret=clean(process.env.MONDAY_TOKEN_ENCRYPTION_KEY)||accountSessionSecret();
  return clientId&&clientSecret&&redirectUri&&encryptionSecret?{clientId,clientSecret,redirectUri,encryptionSecret}:null;
}
const key=secret=>crypto.createHash('sha256').update(String(secret)).digest();
export function encryptMondayToken(value,secret){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key(secret),iv),encrypted=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]),tag=cipher.getAuthTag();return`v1.${iv.toString('base64url')}.${tag.toString('base64url')}.${encrypted.toString('base64url')}`}
export function decryptMondayToken(value,secret){const[v,ivRaw,tagRaw,dataRaw]=String(value||'').split('.');if(v!=='v1'||!ivRaw||!tagRaw||!dataRaw)throw new Error('Stored monday.com token is invalid.');const decipher=crypto.createDecipheriv('aes-256-gcm',key(secret),Buffer.from(ivRaw,'base64url'));decipher.setAuthTag(Buffer.from(tagRaw,'base64url'));return Buffer.concat([decipher.update(Buffer.from(dataRaw,'base64url')),decipher.final()]).toString('utf8')}
function verifier(){return crypto.randomBytes(48).toString('base64url')}
function challenge(v){return crypto.createHash('sha256').update(v).digest('base64url')}
export function createMondayAuthorizationUrl(accountId){const c=mondayConfig();if(!c)throw new Error('monday.com is not configured.');const codeVerifier=verifier(),state=signSession({purpose:'monday-oauth',accountId,codeVerifier},accountSessionSecret(),600),p=new URLSearchParams({client_id:c.clientId,redirect_uri:c.redirectUri,response_type:'code',state,code_challenge:challenge(codeVerifier),code_challenge_method:'S256'});return`${AUTHORIZE_URL}?${p.toString()}`}
export function verifyMondayOAuthState(state,accountId){const p=verifySession(state,accountSessionSecret());return p?.purpose==='monday-oauth'&&p?.accountId===accountId&&clean(p?.codeVerifier)?p:null}
async function tokenRequest(url,body){const response=await fetch(url,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify(body)}),payload=await response.json().catch(()=>({}));return{response,payload}}
export async function exchangeMondayCode(code,codeVerifier){const c=mondayConfig();if(!c)throw new Error('monday.com is not configured.');const modern=await tokenRequest(NEW_TOKEN_URL,{grant_type:'authorization_code',client_id:c.clientId,client_secret:c.clientSecret,code:clean(code),redirect_uri:c.redirectUri,code_verifier:clean(codeVerifier)});if(modern.response.ok&&modern.payload?.access_token)return{...modern.payload,oauth_mode:'oauth2.1'};const legacy=await tokenRequest(LEGACY_TOKEN_URL,{client_id:c.clientId,client_secret:c.clientSecret,code:clean(code),redirect_uri:c.redirectUri});if(legacy.response.ok&&legacy.payload?.access_token)return{...legacy.payload,oauth_mode:'legacy'};const e=new Error(modern.payload?.error_description||modern.payload?.message||modern.payload?.error||legacy.payload?.error_description||legacy.payload?.message||legacy.payload?.error||'monday.com token exchange failed.');e.status=modern.response.status||legacy.response.status||400;throw e}
export async function refreshMondayTokens(refreshToken){const c=mondayConfig(),{response,payload}=await tokenRequest(NEW_TOKEN_URL,{grant_type:'refresh_token',client_id:c.clientId,client_secret:c.clientSecret,refresh_token:clean(refreshToken)});if(!response.ok||!payload?.access_token||!payload?.refresh_token){const e=new Error(payload?.error_description||payload?.message||payload?.error||'monday.com token refresh failed.');e.status=response.status||400;throw e}return payload}
export async function revokeMondayToken(token,tokenType='refresh_token'){const c=mondayConfig();if(!c||!clean(token))return false;const{response}=await tokenRequest(REVOKE_URL,{token:clean(token),client_id:c.clientId,client_secret:c.clientSecret,token_type_hint:tokenType});return response.ok}
export function mondayAccessExpiry(accessToken,tokens={}){if(Number(tokens.expires_in)>0)return new Date(Date.now()+Number(tokens.expires_in)*1000).toISOString();try{const p=String(accessToken||'').split('.');if(p.length===3){const x=JSON.parse(Buffer.from(p[1],'base64url').toString('utf8'));if(Number(x?.exp)>0)return new Date(Number(x.exp)*1000).toISOString()}}catch{}return null}
async function graph(accessToken,query,variables={}){const response=await fetch(API_URL,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:accessToken,'API-Version':API_VERSION},body:JSON.stringify({query,variables})}),payload=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(payload?.error_message||payload?.message||'monday.com API request failed.');e.status=response.status||400;throw e}if(Array.isArray(payload?.errors)&&payload.errors.length){const e=new Error(payload.errors.map(x=>x.message).filter(Boolean).join(' | ')||'monday.com GraphQL request failed.');e.status=400;throw e}return payload?.data||{}}
export async function getMondayIdentity(t){const d=await graph(t,`query { me { id name email title is_admin is_guest account { id name slug active_members_count } } }`),m=d?.me||{};return{userId:clean(m.id),userName:m.name||'',userEmail:m.email||'',userTitle:m.title||'',isAdmin:Boolean(m.is_admin),isGuest:Boolean(m.is_guest),accountId:clean(m.account?.id),accountName:m.account?.name||'',accountSlug:m.account?.slug||'',activeMembers:Number(m.account?.active_members_count||0)}}
export async function listMondayWorkspaces(t){const d=await graph(t,`query { workspaces { id name kind description state } }`);return(d?.workspaces||[]).map(x=>({id:clean(x.id),name:x.name||'Workspace',kind:x.kind||'',description:x.description||'',state:x.state||''})).filter(x=>x.id).slice(0,250)}
export async function listMondayBoards(t){const d=await graph(t,`query { boards(limit: 100) { id name state board_kind workspace { id name } owners { id name } } }`);return(d?.boards||[]).map(x=>({id:clean(x.id),name:x.name||'Board',state:x.state||'',kind:x.board_kind||'',workspaceId:clean(x.workspace?.id),workspaceName:x.workspace?.name||'',owners:Array.isArray(x.owners)?x.owners.map(o=>({id:clean(o.id),name:o.name||'User'})):[]})).filter(x=>x.id)}
export async function listMondayUsers(t){const d=await graph(t,`query { users(limit: 100) { id name email title is_admin is_guest enabled } }`);return(d?.users||[]).map(x=>({id:clean(x.id),name:x.name||x.email||'User',email:x.email||'',title:x.title||'',isAdmin:Boolean(x.is_admin),isGuest:Boolean(x.is_guest),enabled:x.enabled!==false})).filter(x=>x.id)}
export async function listMondayBoardItems(t,boardId,boardName=''){const d=await graph(t,`query GetBoardItems($boardIds: [ID!]) { boards(ids: $boardIds) { id name items_page(limit: 100) { items { id name created_at updated_at group { id title } column_values { id text type column { title } } } } } }`,{boardIds:[String(boardId)]}),b=(d?.boards||[])[0]||{};return(b?.items_page?.items||[]).map(x=>({id:clean(x.id),name:x.name||'Item',boardId:clean(b.id||boardId),boardName:b.name||boardName||'Board',groupId:clean(x.group?.id),groupName:x.group?.title||'',createdAt:x.created_at||null,updatedAt:x.updated_at||null,columns:Array.isArray(x.column_values)?x.column_values.map(c=>({id:clean(c.id),title:c.column?.title||c.id||'Column',type:c.type||'',text:c.text||''})).filter(c=>c.text||c.title):[]})).filter(x=>x.id)}
