import crypto from 'node:crypto';
import { accountSessionSecret, signSession, verifySession } from './session-utils.js';

const clean=value=>String(value??'').trim();
const AUTH_URL='https://zoom.us/oauth/authorize';
const TOKEN_URL='https://zoom.us/oauth/token';
const REVOKE_URL='https://zoom.us/oauth/revoke';
const API_URL='https://api.zoom.us/v2';

export function zoomConfig(){const clientId=clean(process.env.ZOOM_CLIENT_ID),clientSecret=clean(process.env.ZOOM_CLIENT_SECRET),redirectUri=clean(process.env.ZOOM_REDIRECT_URI),encryptionSecret=clean(process.env.ZOOM_TOKEN_ENCRYPTION_KEY)||accountSessionSecret();return clientId&&clientSecret&&redirectUri&&encryptionSecret?{clientId,clientSecret,redirectUri,encryptionSecret}:null}
function cipherKey(secret){return crypto.createHash('sha256').update(String(secret)).digest()}
export function encryptZoomToken(value,secret){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',cipherKey(secret),iv),data=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return`v1.${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${data.toString('base64url')}`}
export function decryptZoomToken(value,secret){const[v,iv,tag,data]=String(value||'').split('.');if(v!=='v1'||!iv||!tag||!data)throw new Error('Stored Zoom token is invalid.');const decipher=crypto.createDecipheriv('aes-256-gcm',cipherKey(secret),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8')}
export function createZoomAuthorizationUrl(accountId){const c=zoomConfig();if(!c)throw new Error('Zoom is not configured.');const state=signSession({purpose:'zoom-oauth',accountId},accountSessionSecret(),10*60);return`${AUTH_URL}?${new URLSearchParams({response_type:'code',client_id:c.clientId,redirect_uri:c.redirectUri,state})}`}
export function verifyZoomOAuthState(state,accountId){const p=verifySession(state,accountSessionSecret());return Boolean(p?.purpose==='zoom-oauth'&&p?.accountId===accountId)}
async function tokenRequest(params){const c=zoomConfig();if(!c)throw new Error('Zoom is not configured.');const response=await fetch(TOKEN_URL,{method:'POST',headers:{Accept:'application/json',Authorization:`Basic ${Buffer.from(`${c.clientId}:${c.clientSecret}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)}),payload=await response.json().catch(()=>({}));if(!response.ok||!payload.access_token){const e=new Error(payload.reason||payload.error_description||payload.error||'Zoom token request failed.');e.status=response.status||400;throw e}return payload}
export const exchangeZoomCode=code=>tokenRequest({grant_type:'authorization_code',code:clean(code),redirect_uri:zoomConfig()?.redirectUri||''});
export const refreshZoomTokens=refreshToken=>tokenRequest({grant_type:'refresh_token',refresh_token:clean(refreshToken)});
export function zoomTokenExpiry(tokens){return new Date(Date.now()+Math.max(60,Number(tokens?.expires_in)||3600)*1000).toISOString()}
export async function revokeZoomToken(token){const c=zoomConfig();if(!c||!clean(token))return;await fetch(REVOKE_URL,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${c.clientId}:${c.clientSecret}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:clean(token)})}).catch(()=>null)}
async function zoomJson(path,{accessToken,method='GET',body}={}){const response=await fetch(`${API_URL}${path}`,{method,headers:{Accept:'application/json',Authorization:`Bearer ${accessToken}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(response.status===204)return{};const payload=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(payload.message||payload.reason||'Zoom API request failed.');e.status=response.status||400;e.code=payload.code;throw e}return payload}
export async function getZoomCurrentUser(accessToken){const x=await zoomJson('/users/me',{accessToken});return{id:clean(x.id),accountId:clean(x.account_id),email:x.email||'',firstName:x.first_name||'',lastName:x.last_name||'',displayName:x.display_name||[x.first_name,x.last_name].filter(Boolean).join(' '),type:Number(x.type||0),timezone:x.timezone||'',status:x.status||'',pmi:String(x.pmi||'')}}
const normalizeMeeting=x=>({id:String(x.id||''),uuid:x.uuid||'',topic:x.topic||'Zoom Meeting',type:Number(x.type||2),status:x.status||'',startTime:x.start_time||null,duration:Number(x.duration||0),timezone:x.timezone||'',agenda:x.agenda||'',joinUrl:x.join_url||'',startUrl:x.start_url||'',createdAt:x.created_at||null,hostId:x.host_id||'',waitingRoom:Boolean(x.settings?.waiting_room),joinBeforeHost:Boolean(x.settings?.join_before_host)});
export async function listZoomMeetings(accessToken){const p=await zoomJson('/users/me/meetings?type=upcoming&page_size=100',{accessToken});return(p.meetings||[]).map(normalizeMeeting)}
export async function getZoomMeeting(accessToken,meetingId){return normalizeMeeting(await zoomJson(`/meetings/${encodeURIComponent(clean(meetingId))}`,{accessToken}))}
function meetingPayload(input){const topic=clean(input.topic);if(!topic)throw Object.assign(new Error('Meeting topic is required.'),{status:422});const duration=Math.max(1,Math.min(1440,Number(input.duration)||30)),start=clean(input.startTime),timezone=clean(input.timezone)||'UTC';if(start&&Number.isNaN(Date.parse(start)))throw Object.assign(new Error('Meeting start time is invalid.'),{status:422});return{topic,type:2,start_time:start||undefined,duration,timezone,agenda:clean(input.agenda),settings:{join_before_host:Boolean(input.joinBeforeHost),waiting_room:input.waitingRoom!==false,mute_upon_entry:true}}}
export async function createZoomMeeting(accessToken,input){return normalizeMeeting(await zoomJson('/users/me/meetings',{accessToken,method:'POST',body:meetingPayload(input)}))}
export async function updateZoomMeeting(accessToken,meetingId,input){await zoomJson(`/meetings/${encodeURIComponent(clean(meetingId))}`,{accessToken,method:'PATCH',body:meetingPayload(input)});return{updated:true,id:clean(meetingId)}}
export async function deleteZoomMeeting(accessToken,meetingId){await zoomJson(`/meetings/${encodeURIComponent(clean(meetingId))}`,{accessToken,method:'DELETE'});return{deleted:true,id:clean(meetingId)}}
