const json=(res,status,payload)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(payload))};
const clean=value=>String(value??'').trim();
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export default async function handler(req,res){
  res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');
  if(req.method==='OPTIONS')return json(res,204,{});if(req.method!=='POST')return json(res,405,{error:'Method not allowed.'});
  const apiKey=clean(process.env.RESEND_API_KEY);const from=clean(process.env.REPORT_FROM_EMAIL);if(!apiKey||!from)return json(res,503,{error:'Report email is not configured.',code:'EMAIL_NOT_CONFIGURED'});
  try{const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const to=clean(body.to);if(!/^\S+@\S+\.\S+$/.test(to))return json(res,422,{error:'Enter a valid email address.'});const title=clean(body.title)||'Creative Creatures Report';const summary=clean(body.summary);const filename=clean(body.filename)||'creative-creatures-report.pdf';const attachments=body.pdfBase64?[{filename,content:clean(body.pdfBase64)}]:undefined;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject:`Creative Creatures - ${title}`,html:`<div style="font-family:Inter,Arial,sans-serif;color:#111218;line-height:1.55"><h1 style="font-size:24px">${escapeHtml(title)}</h1><p>Your Creative Creatures report is attached.</p><pre style="white-space:pre-wrap;background:#f7f7f5;border:1px solid #e5e5e2;border-radius:12px;padding:18px;font-family:Inter,Arial,sans-serif;font-size:13px">${escapeHtml(summary)}</pre></div>`,attachments})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'Email provider rejected the message.');return json(res,200,{sent:true,id:payload.id});}catch(error){console.error('report email error',error);return json(res,500,{error:'The report could not be emailed.',code:'REPORT_EMAIL_ERROR'});}
}
